name = "ayush-pulse"
main = "src/index.js"
compatibility_date = "2024-11-01"

kv_namespaces = [
  { binding = "PULSE_KV", id = "8848075b43044ce9864e3535c62f7b76" }
]

[vars]
ALLOWED_ORIGIN = "https://meetayush2016.github.io"